### ISSUE TITLE
deploying via unlocked node fails

### ISSUE THREAD

**Issue by iemwill** [melonproject/protocol#808] opened 2019-10-16 14:48 UTC
When im trying to follow the instuctions in the README.md to deploy via an unlocked parity node i am getting the Error, that the account is locked.

Since parity throws no error with the suggested command:
```
parity \
  --chain kovan      \
  --rpcport 8545     \
  --auto-update=all  \
  --jsonrpc-apis=all \
  --author <address> \
  --unlock <address> \
  --password <password file>
```
I suggest that the account is unlocked. Do you have any further suggestions for solving this?

In the end i want to deploy a new Version with an exchange module. For also redeploying the Third Parties i use the `development-fresh.json` config and when i'm trying to deploy through Infura i get error messages for using the `.send()` command for the contracts, which is an infura related problem (https://github.com/ethereum/web3.js/issues/1637). So i wanted to try it via parity, but ran into the above described issue.

Thanks for your help!

**Comment by travs** [comment] 2019-10-17 10:32
Hey @iemwill :)

Just as a first step, let's confirm that the account and password match.
I tried parity just now with an incorrect key/password pair, and yet no error was thrown for the snippet you posted.

There are several ways to do this, but this is how I do it:

---

#### Skip if you can confirm they match somehow else

First get [Dapp tools](https://github.com/dapphub/dapptools/blob/master/README.md) `ethsign`. Just follow the instructions there until you have `ethsign` available.

Then put this in a script and edit/run it
```sh
ADDR=0xyouraddress
PASS=/path/to/password/file
KEYS=/path/to/wallet/directory # this is where your kovan keys are kept
# on linux KEYS would be ~/.local/share/io.parity.ethereum/keys/kovan/

ethsign msg --data 0xabcd $ADDR --passphrase-file $PASS --key-store $KEYS \
  && echo pass || echo fail
```

---

If the account and password do indeed match, then please post the error message and also which program is throwing the error.
Is it parity itself, or some intermediary code? If it is intermediary code please include a trace of where the error was exactly.

**Comment by travs** [comment] 2019-10-17 10:41
In the meantime I am syncing a local kovan node to attempt to reproduce this (may take  little while).

I can say though, that I have not run into any issues with deploying to kovan over infura, but perhaps that is due to us using different web3 versions or something like that.

**Comment by iemwill** [comment] 2019-10-17 17:00
thx for the fast answer! Gonna check it out tomorrow. Tried just Ropsten till now, maybe also a scaling issue :)

**Comment by iemwill** [comment] 2019-10-18 13:34
But actually i can confirm, that the password stuff havent been a problem because somehow the first transaction went 2-3 times through, but never a second...

**Comment by iemwill** [comment] 2019-10-18 13:36
In general i tried very much different combinations but all just on Ropsten Testnet. Sometimes the terminal kept repeating infinite the confirmation from calling .totalSupply() the first deployed token...

**Comment by travs** [comment] 2019-10-18 17:18
Ok thanks @iemwill 

Hmm, I have to say I'm not able to diagnose what the problem could be without an error message.
Based on what you're saying though, it doesn't sound like an issue with our deployment script itself, but perhaps with the node connectivity and/or account situation.

My parity node is still syncing unfortunately, but I did try deploying with the config file you mentioned via infura and got the error you mentioned (`eth_sendTransaction does not exist`). This only occurred after a bunch of tx went through already though, so I'm pretty sure it only causes a problem when trying to call a function on a contract, rather than deploying a contract itself.

I still don't recall this issue from before though, but the I think I was using a local node most of the time while working on this as well.

**Comment by iemwill** [comment] 2019-10-19 21:32
> ADDR=0xyouraddress
PASS=/path/to/password/file
KEYS=/path/to/wallet/directory # this is where your kovan keys are kept
# on linux KEYS would be ~/.local/share/io.parity.ethereum/keys/kovan/

ethsign msg --data 0xabcd $ADDR --passphrase-file $PASS --key-store $KEYS \
  && echo pass || echo fail

returns hexcode and pass but was missing `--from` in front of $ADDR

I found the error `eth_sendTransaction does not exist` happening because line 88 in `/src/utils/deploy/deployThirdParty.ts` and Infura. Because it is not a sendRawTx infura is not able to handle this request. This error comes always during deploy through infura at this or any other `.send()` command.

**Comment by iemwill** [comment] 2019-10-20 01:03
now i am getting this, after few seconds:
```
$ node bin/melon.js deploy --config deployments/configs/test/fresh.json --gas-price 3000000000
Deploying thirdParty & melon contracts.
Loaded config from ../deployments/configs/test/fresh.json
With unlocked node
Node has 17 peers
2019-10-20T01:00:35.844Z error melon:protocol:utils:solidity:deploy: "Deploy transaction error" "WETH()" {}
Deploy transaction error WETH(): Failed to check for transaction receipt:
{}
```
guess the await for the txReceipt does not work well caused by parity maybe...

**Comment by travs** [comment] 2019-10-20 12:55
@iemwill 

Thank you for these error messages, they really helped.

I am still unable to get my node to sync due to wifi data limits on my connection, so I can't really do much testing there at the moment.
I should be able to get this working over infura though, which is good enough for now.
The issue does indeed seem to be that some of our transactions use `send` instead of `sendRawTransaction`. so I'm now working on finding each of those in the path of our deploy script, and changing them to send the signed, raw form instead.

I will ping you again once I've done this.

**Comment by travs** [comment] 2019-10-22 07:58
@iemwill 

Ok, so I am finally able to deploy the whole thing over infura on kovan. The main problem was the kyber setup, but it's fixed in the `setup-on-behalf` branch. You can install directly from that branch to get those changes. Grep through the files for `"NB"` to find a couple values you can modify (it's about send ETH/WETH; you may need to send more/less than we do).

Also, you will need to use a config a bit like [this](https://git.io/JeRKe) with the `track` and `chain` defined.

What would possibly be easier for you guys though, might be to use our kyber system by filling in the `DEPLOY` stuff with addresses you can find in our [current deployment](https://github.com/melonproject/protocol/blob/master/deployments/kovan-kyberPrice.json).

**Comment by iemwill** [comment] 2019-10-22 12:32
Thanks for that!
The thing is, for the GivethModule we are implementing we need to setup the testenvironment on Ropsten Testnet because the giveth Contract we need to call is on Ropsten.

For a Mainnet deployment, we need to call the Contract from giveth on Mainnet.

**Comment by travs** [comment] 2019-10-24 06:25
@iemwill Gotcha, well this should work over infura now anyway :)

**Closed by travs** 2019-10-24 06:25 UTC

**Comment by iemwill** [comment] 2019-10-29 20:49
Try it right now. Got problems witch changing the Track, how is that possible? (To change the Track...)

**Comment by iemwill** [comment] 2019-10-29 22:19
deploy worked, thx!
